Use Case EventChecker: renamed isValid...() to checkValid...(), changed return type to void since any false case will return an appropriate exception instead of false. EventManager:  fixed an issue where a talk with a non existent speaker could be added. restructured all change...() methods to use EventChecker methods instead. EventModifier: focuses solely on setting fields of an event, removed duplicate checking of valid event, delegated to EventChecker instead via EventManager
Throwables
ObjectNotFoundException: added an extra constructor to specify type of object that could not be found

Controller
RegistrationController, OrganizerController: added a helper method to automatically update all keys in ConversationManager, FriendManager, EventManager (for speakers)

Miscellaneous
inspected and restructured all throw statements in EventManager, EventChecker, and EventModifer